import { generateUUIDv7 } from './utils'

// Hotel-related object models for complex structures
export const hotelModelsData = [
  {
    uuid: generateUUIDv7(),
    name: 'Hotel Building',
    abbreviation: 'HT',
    version: '1.0',
    description:
      'Complete hotel building model with multiple floors, rooms and facilities',
    creator: 'System',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    properties: [
      {
        uuid: generateUUIDv7(),
        key: 'Total Floors',
        values: [{ uuid: generateUUIDv7(), value: 'Variable', files: [] }],
        files: [],
      },
      {
        uuid: generateUUIDv7(),
        key: 'Building Height',
        values: [{ uuid: generateUUIDv7(), value: 'Variable', files: [] }],
        files: [],
      },
      {
        uuid: generateUUIDv7(),
        key: 'Construction Year',
        values: [{ uuid: generateUUIDv7(), value: 'Variable', files: [] }],
        files: [],
      },
      {
        uuid: generateUUIDv7(),
        key: 'Building Class',
        values: [{ uuid: generateUUIDv7(), value: 'Variable', files: [] }],
        files: [],
      },
      {
        uuid: generateUUIDv7(),
        key: 'Energy Rating',
        values: [{ uuid: generateUUIDv7(), value: 'Variable', files: [] }],
        files: [],
      },
    ],
    files: [],
  },
  {
    uuid: generateUUIDv7(),
    name: 'Hotel Floor',
    abbreviation: 'FL',
    version: '1.0',
    description: 'Floor model for hotel buildings with multiple room types',
    creator: 'System',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    properties: [
      {
        uuid: generateUUIDv7(),
        key: 'Floor Number',
        values: [{ uuid: generateUUIDv7(), value: 'Variable', files: [] }],
        files: [],
      },
      {
        uuid: generateUUIDv7(),
        key: 'Floor Area',
        values: [{ uuid: generateUUIDv7(), value: 'Variable', files: [] }],
        files: [],
      },
      {
        uuid: generateUUIDv7(),
        key: 'Room Count',
        values: [{ uuid: generateUUIDv7(), value: 'Variable', files: [] }],
        files: [],
      },
      {
        uuid: generateUUIDv7(),
        key: 'Ceiling Height',
        values: [{ uuid: generateUUIDv7(), value: 'Variable', files: [] }],
        files: [],
      },
      {
        uuid: generateUUIDv7(),
        key: 'Emergency Exits',
        values: [{ uuid: generateUUIDv7(), value: 'Variable', files: [] }],
        files: [],
      },
    ],
    files: [],
  },
  {
    uuid: generateUUIDv7(),
    name: 'Standard Room',
    abbreviation: 'SR',
    version: '1.0',
    description: 'Standard hotel room with basic amenities',
    creator: 'System',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    properties: [
      {
        uuid: generateUUIDv7(),
        key: 'Room Number',
        values: [{ uuid: generateUUIDv7(), value: 'Variable', files: [] }],
        files: [],
      },
      {
        uuid: generateUUIDv7(),
        key: 'Room Area',
        values: [{ uuid: generateUUIDv7(), value: 'Variable', files: [] }],
        files: [],
      },
      {
        uuid: generateUUIDv7(),
        key: 'Bed Type',
        values: [{ uuid: generateUUIDv7(), value: 'Variable', files: [] }],
        files: [],
      },
      {
        uuid: generateUUIDv7(),
        key: 'Max Occupancy',
        values: [{ uuid: generateUUIDv7(), value: 'Variable', files: [] }],
        files: [],
      },
      {
        uuid: generateUUIDv7(),
        key: 'View Type',
        values: [{ uuid: generateUUIDv7(), value: 'Variable', files: [] }],
        files: [],
      },
    ],
    files: [],
  },
  {
    uuid: generateUUIDv7(),
    name: 'Deluxe Room',
    abbreviation: 'DR',
    version: '1.0',
    description: 'Deluxe hotel room with premium amenities',
    creator: 'System',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    properties: [
      {
        uuid: generateUUIDv7(),
        key: 'Room Number',
        values: [{ uuid: generateUUIDv7(), value: 'Variable', files: [] }],
        files: [],
      },
      {
        uuid: generateUUIDv7(),
        key: 'Room Area',
        values: [{ uuid: generateUUIDv7(), value: 'Variable', files: [] }],
        files: [],
      },
      {
        uuid: generateUUIDv7(),
        key: 'Bed Type',
        values: [{ uuid: generateUUIDv7(), value: 'Variable', files: [] }],
        files: [],
      },
      {
        uuid: generateUUIDv7(),
        key: 'Max Occupancy',
        values: [{ uuid: generateUUIDv7(), value: 'Variable', files: [] }],
        files: [],
      },
      {
        uuid: generateUUIDv7(),
        key: 'View Type',
        values: [{ uuid: generateUUIDv7(), value: 'Variable', files: [] }],
        files: [],
      },
      {
        uuid: generateUUIDv7(),
        key: 'Premium Features',
        values: [{ uuid: generateUUIDv7(), value: 'Variable', files: [] }],
        files: [],
      },
    ],
    files: [],
  },
  {
    uuid: generateUUIDv7(),
    name: 'Suite',
    abbreviation: 'ST',
    version: '1.0',
    description:
      'Luxury suite with separate living areas and premium amenities',
    creator: 'System',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    properties: [
      {
        uuid: generateUUIDv7(),
        key: 'Suite Number',
        values: [{ uuid: generateUUIDv7(), value: 'Variable', files: [] }],
        files: [],
      },
      {
        uuid: generateUUIDv7(),
        key: 'Total Area',
        values: [{ uuid: generateUUIDv7(), value: 'Variable', files: [] }],
        files: [],
      },
      {
        uuid: generateUUIDv7(),
        key: 'Bedrooms',
        values: [{ uuid: generateUUIDv7(), value: 'Variable', files: [] }],
        files: [],
      },
      {
        uuid: generateUUIDv7(),
        key: 'Bathrooms',
        values: [{ uuid: generateUUIDv7(), value: 'Variable', files: [] }],
        files: [],
      },
      {
        uuid: generateUUIDv7(),
        key: 'View Type',
        values: [{ uuid: generateUUIDv7(), value: 'Variable', files: [] }],
        files: [],
      },
      {
        uuid: generateUUIDv7(),
        key: 'Special Features',
        values: [{ uuid: generateUUIDv7(), value: 'Variable', files: [] }],
        files: [],
      },
    ],
    files: [],
  },
  {
    uuid: generateUUIDv7(),
    name: 'Bathroom',
    abbreviation: 'BT',
    version: '1.0',
    description: 'Hotel room bathroom with fixtures and fittings',
    creator: 'System',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    properties: [
      {
        uuid: generateUUIDv7(),
        key: 'Bathroom Type',
        values: [{ uuid: generateUUIDv7(), value: 'Variable', files: [] }],
        files: [],
      },
      {
        uuid: generateUUIDv7(),
        key: 'Size',
        values: [{ uuid: generateUUIDv7(), value: 'Variable', files: [] }],
        files: [],
      },
      {
        uuid: generateUUIDv7(),
        key: 'Fixtures',
        values: [{ uuid: generateUUIDv7(), value: 'Variable', files: [] }],
        files: [],
      },
      {
        uuid: generateUUIDv7(),
        key: 'Flooring Material',
        values: [{ uuid: generateUUIDv7(), value: 'Variable', files: [] }],
        files: [],
      },
      {
        uuid: generateUUIDv7(),
        key: 'Wall Material',
        values: [{ uuid: generateUUIDv7(), value: 'Variable', files: [] }],
        files: [],
      },
    ],
    files: [],
  },
  {
    uuid: generateUUIDv7(),
    name: 'Furniture Item',
    abbreviation: 'FI',
    version: '1.0',
    description: 'Furniture items used in hotel rooms and common areas',
    creator: 'System',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    properties: [
      {
        uuid: generateUUIDv7(),
        key: 'Item Type',
        values: [{ uuid: generateUUIDv7(), value: 'Variable', files: [] }],
        files: [],
      },
      {
        uuid: generateUUIDv7(),
        key: 'Material',
        values: [{ uuid: generateUUIDv7(), value: 'Variable', files: [] }],
        files: [],
      },
      {
        uuid: generateUUIDv7(),
        key: 'Dimensions',
        values: [{ uuid: generateUUIDv7(), value: 'Variable', files: [] }],
        files: [],
      },
      {
        uuid: generateUUIDv7(),
        key: 'Manufacturer',
        values: [{ uuid: generateUUIDv7(), value: 'Variable', files: [] }],
        files: [],
      },
      {
        uuid: generateUUIDv7(),
        key: 'Year Purchased',
        values: [{ uuid: generateUUIDv7(), value: 'Variable', files: [] }],
        files: [],
      },
    ],
    files: [],
  },
  {
    uuid: generateUUIDv7(),
    name: 'Facility',
    abbreviation: 'FC',
    version: '1.0',
    description: 'Common facilities in the hotel like gyms, pools, restaurants',
    creator: 'System',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    properties: [
      {
        uuid: generateUUIDv7(),
        key: 'Facility Type',
        values: [{ uuid: generateUUIDv7(), value: 'Variable', files: [] }],
        files: [],
      },
      {
        uuid: generateUUIDv7(),
        key: 'Location',
        values: [{ uuid: generateUUIDv7(), value: 'Variable', files: [] }],
        files: [],
      },
      {
        uuid: generateUUIDv7(),
        key: 'Size',
        values: [{ uuid: generateUUIDv7(), value: 'Variable', files: [] }],
        files: [],
      },
      {
        uuid: generateUUIDv7(),
        key: 'Capacity',
        values: [{ uuid: generateUUIDv7(), value: 'Variable', files: [] }],
        files: [],
      },
      {
        uuid: generateUUIDv7(),
        key: 'Opening Hours',
        values: [{ uuid: generateUUIDv7(), value: 'Variable', files: [] }],
        files: [],
      },
    ],
    files: [],
  },
  {
    uuid: generateUUIDv7(),
    name: 'Elevator',
    abbreviation: 'EL',
    version: '1.0',
    description: 'Elevator systems in the hotel building',
    creator: 'System',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    properties: [
      {
        uuid: generateUUIDv7(),
        key: 'Elevator Number',
        values: [{ uuid: generateUUIDv7(), value: 'Variable', files: [] }],
        files: [],
      },
      {
        uuid: generateUUIDv7(),
        key: 'Type',
        values: [{ uuid: generateUUIDv7(), value: 'Variable', files: [] }],
        files: [],
      },
      {
        uuid: generateUUIDv7(),
        key: 'Capacity',
        values: [{ uuid: generateUUIDv7(), value: 'Variable', files: [] }],
        files: [],
      },
      {
        uuid: generateUUIDv7(),
        key: 'Manufacturer',
        values: [{ uuid: generateUUIDv7(), value: 'Variable', files: [] }],
        files: [],
      },
      {
        uuid: generateUUIDv7(),
        key: 'Installation Date',
        values: [{ uuid: generateUUIDv7(), value: 'Variable', files: [] }],
        files: [],
      },
    ],
    files: [],
  },
  {
    uuid: generateUUIDv7(),
    name: 'HVAC Unit',
    abbreviation: 'HV',
    version: '1.0',
    description: 'Heating, ventilation, and air conditioning systems',
    creator: 'System',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    properties: [
      {
        uuid: generateUUIDv7(),
        key: 'Unit Number',
        values: [{ uuid: generateUUIDv7(), value: 'Variable', files: [] }],
        files: [],
      },
      {
        uuid: generateUUIDv7(),
        key: 'Type',
        values: [{ uuid: generateUUIDv7(), value: 'Variable', files: [] }],
        files: [],
      },
      {
        uuid: generateUUIDv7(),
        key: 'Capacity',
        values: [{ uuid: generateUUIDv7(), value: 'Variable', files: [] }],
        files: [],
      },
      {
        uuid: generateUUIDv7(),
        key: 'Manufacturer',
        values: [{ uuid: generateUUIDv7(), value: 'Variable', files: [] }],
        files: [],
      },
      {
        uuid: generateUUIDv7(),
        key: 'Installation Date',
        values: [{ uuid: generateUUIDv7(), value: 'Variable', files: [] }],
        files: [],
      },
    ],
    files: [],
  },
  {
    uuid: generateUUIDv7(),
    name: 'Security System',
    abbreviation: 'SS',
    version: '1.0',
    description:
      'Hotel security systems including cameras, alarms, and access controls',
    creator: 'System',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    properties: [
      {
        uuid: generateUUIDv7(),
        key: 'System Type',
        values: [{ uuid: generateUUIDv7(), value: 'Variable', files: [] }],
        files: [],
      },
      {
        uuid: generateUUIDv7(),
        key: 'Coverage Area',
        values: [{ uuid: generateUUIDv7(), value: 'Variable', files: [] }],
        files: [],
      },
      {
        uuid: generateUUIDv7(),
        key: 'Manufacturer',
        values: [{ uuid: generateUUIDv7(), value: 'Variable', files: [] }],
        files: [],
      },
      {
        uuid: generateUUIDv7(),
        key: 'Installation Date',
        values: [{ uuid: generateUUIDv7(), value: 'Variable', files: [] }],
        files: [],
      },
      {
        uuid: generateUUIDv7(),
        key: 'Maintenance Schedule',
        values: [{ uuid: generateUUIDv7(), value: 'Variable', files: [] }],
        files: [],
      },
    ],
    files: [],
  },
  {
    uuid: generateUUIDv7(),
    name: 'Room Amenity',
    abbreviation: 'RA',
    version: '1.0',
    description: 'Amenities provided in hotel rooms',
    creator: 'System',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    properties: [
      {
        uuid: generateUUIDv7(),
        key: 'Amenity Type',
        values: [{ uuid: generateUUIDv7(), value: 'Variable', files: [] }],
        files: [],
      },
      {
        uuid: generateUUIDv7(),
        key: 'Brand',
        values: [{ uuid: generateUUIDv7(), value: 'Variable', files: [] }],
        files: [],
      },
      {
        uuid: generateUUIDv7(),
        key: 'Description',
        values: [{ uuid: generateUUIDv7(), value: 'Variable', files: [] }],
        files: [],
      },
      {
        uuid: generateUUIDv7(),
        key: 'Replacement Schedule',
        values: [{ uuid: generateUUIDv7(), value: 'Variable', files: [] }],
        files: [],
      },
    ],
    files: [],
  },
  {
    uuid: generateUUIDv7(),
    name: 'Plumbing System',
    abbreviation: 'PS',
    version: '1.0',
    description: 'Water supply and drainage systems',
    creator: 'System',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    properties: [
      {
        uuid: generateUUIDv7(),
        key: 'System Type',
        values: [{ uuid: generateUUIDv7(), value: 'Variable', files: [] }],
        files: [],
      },
      {
        uuid: generateUUIDv7(),
        key: 'Material',
        values: [{ uuid: generateUUIDv7(), value: 'Variable', files: [] }],
        files: [],
      },
      {
        uuid: generateUUIDv7(),
        key: 'Installation Date',
        values: [{ uuid: generateUUIDv7(), value: 'Variable', files: [] }],
        files: [],
      },
      {
        uuid: generateUUIDv7(),
        key: 'Service Area',
        values: [{ uuid: generateUUIDv7(), value: 'Variable', files: [] }],
        files: [],
      },
      {
        uuid: generateUUIDv7(),
        key: 'Maintenance Schedule',
        values: [{ uuid: generateUUIDv7(), value: 'Variable', files: [] }],
        files: [],
      },
    ],
    files: [],
  },
  {
    uuid: generateUUIDv7(),
    name: 'Electrical System',
    abbreviation: 'ES',
    version: '1.0',
    description: 'Electrical distribution and power systems',
    creator: 'System',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    properties: [
      {
        uuid: generateUUIDv7(),
        key: 'System Type',
        values: [{ uuid: generateUUIDv7(), value: 'Variable', files: [] }],
        files: [],
      },
      {
        uuid: generateUUIDv7(),
        key: 'Capacity',
        values: [{ uuid: generateUUIDv7(), value: 'Variable', files: [] }],
        files: [],
      },
      {
        uuid: generateUUIDv7(),
        key: 'Installation Date',
        values: [{ uuid: generateUUIDv7(), value: 'Variable', files: [] }],
        files: [],
      },
      {
        uuid: generateUUIDv7(),
        key: 'Service Area',
        values: [{ uuid: generateUUIDv7(), value: 'Variable', files: [] }],
        files: [],
      },
      {
        uuid: generateUUIDv7(),
        key: 'Backup Systems',
        values: [{ uuid: generateUUIDv7(), value: 'Variable', files: [] }],
        files: [],
      },
    ],
    files: [],
  },
  {
    uuid: generateUUIDv7(),
    name: 'Room Technology',
    abbreviation: 'RT',
    version: '1.0',
    description: 'Technology systems in hotel rooms',
    creator: 'System',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    properties: [
      {
        uuid: generateUUIDv7(),
        key: 'Technology Type',
        values: [{ uuid: generateUUIDv7(), value: 'Variable', files: [] }],
        files: [],
      },
      {
        uuid: generateUUIDv7(),
        key: 'Manufacturer',
        values: [{ uuid: generateUUIDv7(), value: 'Variable', files: [] }],
        files: [],
      },
      {
        uuid: generateUUIDv7(),
        key: 'Model',
        values: [{ uuid: generateUUIDv7(), value: 'Variable', files: [] }],
        files: [],
      },
      {
        uuid: generateUUIDv7(),
        key: 'Installation Date',
        values: [{ uuid: generateUUIDv7(), value: 'Variable', files: [] }],
        files: [],
      },
      {
        uuid: generateUUIDv7(),
        key: 'Warranty Expiration',
        values: [{ uuid: generateUUIDv7(), value: 'Variable', files: [] }],
        files: [],
      },
    ],
    files: [],
  },
]
