import { generateUUIDv7 } from './utils'

// School-related object models for complex structures
export const schoolModelsData = [
  {
    uuid: generateUUIDv7(),
    name: 'School Building',
    abbreviation: 'SB',
    version: '1.0',
    description:
      'Complete school building model with multiple floors, classrooms and facilities',
    creator: 'System',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    properties: [
      {
        uuid: generateUUIDv7(),
        key: 'Total Floors',
        values: [{ uuid: generateUUIDv7(), value: 'Variable', files: [] }],
        files: [],
      },
      {
        uuid: generateUUIDv7(),
        key: 'Building Height',
        values: [{ uuid: generateUUIDv7(), value: 'Variable', files: [] }],
        files: [],
      },
      {
        uuid: generateUUIDv7(),
        key: 'Construction Year',
        values: [{ uuid: generateUUIDv7(), value: 'Variable', files: [] }],
        files: [],
      },
      {
        uuid: generateUUIDv7(),
        key: 'Building Class',
        values: [{ uuid: generateUUIDv7(), value: 'Variable', files: [] }],
        files: [],
      },
      {
        uuid: generateUUIDv7(),
        key: 'Energy Rating',
        values: [{ uuid: generateUUIDv7(), value: 'Variable', files: [] }],
        files: [],
      },
    ],
    files: [],
  },
  {
    uuid: generateUUIDv7(),
    name: 'School Floor',
    abbreviation: 'SF',
    version: '1.0',
    description:
      'Floor model for school buildings with multiple classroom types',
    creator: 'System',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    properties: [
      {
        uuid: generateUUIDv7(),
        key: 'Floor Number',
        values: [{ uuid: generateUUIDv7(), value: 'Variable', files: [] }],
        files: [],
      },
      {
        uuid: generateUUIDv7(),
        key: 'Floor Area',
        values: [{ uuid: generateUUIDv7(), value: 'Variable', files: [] }],
        files: [],
      },
      {
        uuid: generateUUIDv7(),
        key: 'Classroom Count',
        values: [{ uuid: generateUUIDv7(), value: 'Variable', files: [] }],
        files: [],
      },
      {
        uuid: generateUUIDv7(),
        key: 'Ceiling Height',
        values: [{ uuid: generateUUIDv7(), value: 'Variable', files: [] }],
        files: [],
      },
      {
        uuid: generateUUIDv7(),
        key: 'Emergency Exits',
        values: [{ uuid: generateUUIDv7(), value: 'Variable', files: [] }],
        files: [],
      },
    ],
    files: [],
  },
  {
    uuid: generateUUIDv7(),
    name: 'Standard Classroom',
    abbreviation: 'SC',
    version: '1.0',
    description: 'Standard classroom with basic educational equipment',
    creator: 'System',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    properties: [
      {
        uuid: generateUUIDv7(),
        key: 'Room Number',
        values: [{ uuid: generateUUIDv7(), value: 'Variable', files: [] }],
        files: [],
      },
      {
        uuid: generateUUIDv7(),
        key: 'Room Area',
        values: [{ uuid: generateUUIDv7(), value: 'Variable', files: [] }],
        files: [],
      },
      {
        uuid: generateUUIDv7(),
        key: 'Student Capacity',
        values: [{ uuid: generateUUIDv7(), value: 'Variable', files: [] }],
        files: [],
      },
      {
        uuid: generateUUIDv7(),
        key: 'Subject Focus',
        values: [{ uuid: generateUUIDv7(), value: 'Variable', files: [] }],
        files: [],
      },
      {
        uuid: generateUUIDv7(),
        key: 'Layout Type',
        values: [{ uuid: generateUUIDv7(), value: 'Variable', files: [] }],
        files: [],
      },
    ],
    files: [],
  },
  {
    uuid: generateUUIDv7(),
    name: 'Specialized Classroom',
    abbreviation: 'SP',
    version: '1.0',
    description:
      'Specialized classroom with advanced equipment for specific subjects',
    creator: 'System',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    properties: [
      {
        uuid: generateUUIDv7(),
        key: 'Room Number',
        values: [{ uuid: generateUUIDv7(), value: 'Variable', files: [] }],
        files: [],
      },
      {
        uuid: generateUUIDv7(),
        key: 'Room Area',
        values: [{ uuid: generateUUIDv7(), value: 'Variable', files: [] }],
        files: [],
      },
      {
        uuid: generateUUIDv7(),
        key: 'Student Capacity',
        values: [{ uuid: generateUUIDv7(), value: 'Variable', files: [] }],
        files: [],
      },
      {
        uuid: generateUUIDv7(),
        key: 'Specialty Type',
        values: [{ uuid: generateUUIDv7(), value: 'Variable', files: [] }],
        files: [],
      },
      {
        uuid: generateUUIDv7(),
        key: 'Equipment Level',
        values: [{ uuid: generateUUIDv7(), value: 'Variable', files: [] }],
        files: [],
      },
      {
        uuid: generateUUIDv7(),
        key: 'Special Features',
        values: [{ uuid: generateUUIDv7(), value: 'Variable', files: [] }],
        files: [],
      },
    ],
    files: [],
  },
  {
    uuid: generateUUIDv7(),
    name: 'Laboratory',
    abbreviation: 'LB',
    version: '1.0',
    description:
      'Science laboratory with specialized equipment for experiments',
    creator: 'System',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    properties: [
      {
        uuid: generateUUIDv7(),
        key: 'Lab Number',
        values: [{ uuid: generateUUIDv7(), value: 'Variable', files: [] }],
        files: [],
      },
      {
        uuid: generateUUIDv7(),
        key: 'Total Area',
        values: [{ uuid: generateUUIDv7(), value: 'Variable', files: [] }],
        files: [],
      },
      {
        uuid: generateUUIDv7(),
        key: 'Student Capacity',
        values: [{ uuid: generateUUIDv7(), value: 'Variable', files: [] }],
        files: [],
      },
      {
        uuid: generateUUIDv7(),
        key: 'Lab Type',
        values: [{ uuid: generateUUIDv7(), value: 'Variable', files: [] }],
        files: [],
      },
      {
        uuid: generateUUIDv7(),
        key: 'Safety Features',
        values: [{ uuid: generateUUIDv7(), value: 'Variable', files: [] }],
        files: [],
      },
      {
        uuid: generateUUIDv7(),
        key: 'Special Equipment',
        values: [{ uuid: generateUUIDv7(), value: 'Variable', files: [] }],
        files: [],
      },
    ],
    files: [],
  },
  {
    uuid: generateUUIDv7(),
    name: 'Staff Room',
    abbreviation: 'SR',
    version: '1.0',
    description: 'Teacher and staff workspace and break area',
    creator: 'System',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    properties: [
      {
        uuid: generateUUIDv7(),
        key: 'Room Type',
        values: [{ uuid: generateUUIDv7(), value: 'Variable', files: [] }],
        files: [],
      },
      {
        uuid: generateUUIDv7(),
        key: 'Size',
        values: [{ uuid: generateUUIDv7(), value: 'Variable', files: [] }],
        files: [],
      },
      {
        uuid: generateUUIDv7(),
        key: 'Capacity',
        values: [{ uuid: generateUUIDv7(), value: 'Variable', files: [] }],
        files: [],
      },
      {
        uuid: generateUUIDv7(),
        key: 'Amenities',
        values: [{ uuid: generateUUIDv7(), value: 'Variable', files: [] }],
        files: [],
      },
      {
        uuid: generateUUIDv7(),
        key: 'Department',
        values: [{ uuid: generateUUIDv7(), value: 'Variable', files: [] }],
        files: [],
      },
    ],
    files: [],
  },
  {
    uuid: generateUUIDv7(),
    name: 'Furniture Item',
    abbreviation: 'FI',
    version: '1.0',
    description: 'Furniture items used in classrooms and common areas',
    creator: 'System',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    properties: [
      {
        uuid: generateUUIDv7(),
        key: 'Item Type',
        values: [{ uuid: generateUUIDv7(), value: 'Variable', files: [] }],
        files: [],
      },
      {
        uuid: generateUUIDv7(),
        key: 'Material',
        values: [{ uuid: generateUUIDv7(), value: 'Variable', files: [] }],
        files: [],
      },
      {
        uuid: generateUUIDv7(),
        key: 'Dimensions',
        values: [{ uuid: generateUUIDv7(), value: 'Variable', files: [] }],
        files: [],
      },
      {
        uuid: generateUUIDv7(),
        key: 'Manufacturer',
        values: [{ uuid: generateUUIDv7(), value: 'Variable', files: [] }],
        files: [],
      },
      {
        uuid: generateUUIDv7(),
        key: 'Year Purchased',
        values: [{ uuid: generateUUIDv7(), value: 'Variable', files: [] }],
        files: [],
      },
    ],
    files: [],
  },
  {
    uuid: generateUUIDv7(),
    name: 'Facility',
    abbreviation: 'FC',
    version: '1.0',
    description:
      'Common facilities in the school like gyms, auditoriums, cafeterias',
    creator: 'System',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    properties: [
      {
        uuid: generateUUIDv7(),
        key: 'Facility Type',
        values: [{ uuid: generateUUIDv7(), value: 'Variable', files: [] }],
        files: [],
      },
      {
        uuid: generateUUIDv7(),
        key: 'Location',
        values: [{ uuid: generateUUIDv7(), value: 'Variable', files: [] }],
        files: [],
      },
      {
        uuid: generateUUIDv7(),
        key: 'Size',
        values: [{ uuid: generateUUIDv7(), value: 'Variable', files: [] }],
        files: [],
      },
      {
        uuid: generateUUIDv7(),
        key: 'Capacity',
        values: [{ uuid: generateUUIDv7(), value: 'Variable', files: [] }],
        files: [],
      },
      {
        uuid: generateUUIDv7(),
        key: 'Usage Hours',
        values: [{ uuid: generateUUIDv7(), value: 'Variable', files: [] }],
        files: [],
      },
    ],
    files: [],
  },
  {
    uuid: generateUUIDv7(),
    name: 'Library',
    abbreviation: 'LI',
    version: '1.0',
    description: 'School library with books, study areas, and resources',
    creator: 'System',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    properties: [
      {
        uuid: generateUUIDv7(),
        key: 'Total Area',
        values: [{ uuid: generateUUIDv7(), value: 'Variable', files: [] }],
        files: [],
      },
      {
        uuid: generateUUIDv7(),
        key: 'Seating Capacity',
        values: [{ uuid: generateUUIDv7(), value: 'Variable', files: [] }],
        files: [],
      },
      {
        uuid: generateUUIDv7(),
        key: 'Book Collection Size',
        values: [{ uuid: generateUUIDv7(), value: 'Variable', files: [] }],
        files: [],
      },
      {
        uuid: generateUUIDv7(),
        key: 'Digital Resources',
        values: [{ uuid: generateUUIDv7(), value: 'Variable', files: [] }],
        files: [],
      },
      {
        uuid: generateUUIDv7(),
        key: 'Special Collections',
        values: [{ uuid: generateUUIDv7(), value: 'Variable', files: [] }],
        files: [],
      },
    ],
    files: [],
  },
  {
    uuid: generateUUIDv7(),
    name: 'HVAC Unit',
    abbreviation: 'HV',
    version: '1.0',
    description: 'Heating, ventilation, and air conditioning systems',
    creator: 'System',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    properties: [
      {
        uuid: generateUUIDv7(),
        key: 'Unit Number',
        values: [{ uuid: generateUUIDv7(), value: 'Variable', files: [] }],
        files: [],
      },
      {
        uuid: generateUUIDv7(),
        key: 'Type',
        values: [{ uuid: generateUUIDv7(), value: 'Variable', files: [] }],
        files: [],
      },
      {
        uuid: generateUUIDv7(),
        key: 'Capacity',
        values: [{ uuid: generateUUIDv7(), value: 'Variable', files: [] }],
        files: [],
      },
      {
        uuid: generateUUIDv7(),
        key: 'Manufacturer',
        values: [{ uuid: generateUUIDv7(), value: 'Variable', files: [] }],
        files: [],
      },
      {
        uuid: generateUUIDv7(),
        key: 'Installation Date',
        values: [{ uuid: generateUUIDv7(), value: 'Variable', files: [] }],
        files: [],
      },
    ],
    files: [],
  },
  {
    uuid: generateUUIDv7(),
    name: 'Security System',
    abbreviation: 'SS',
    version: '1.0',
    description:
      'School security systems including cameras, alarms, and access controls',
    creator: 'System',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    properties: [
      {
        uuid: generateUUIDv7(),
        key: 'System Type',
        values: [{ uuid: generateUUIDv7(), value: 'Variable', files: [] }],
        files: [],
      },
      {
        uuid: generateUUIDv7(),
        key: 'Coverage Area',
        values: [{ uuid: generateUUIDv7(), value: 'Variable', files: [] }],
        files: [],
      },
      {
        uuid: generateUUIDv7(),
        key: 'Manufacturer',
        values: [{ uuid: generateUUIDv7(), value: 'Variable', files: [] }],
        files: [],
      },
      {
        uuid: generateUUIDv7(),
        key: 'Installation Date',
        values: [{ uuid: generateUUIDv7(), value: 'Variable', files: [] }],
        files: [],
      },
      {
        uuid: generateUUIDv7(),
        key: 'Maintenance Schedule',
        values: [{ uuid: generateUUIDv7(), value: 'Variable', files: [] }],
        files: [],
      },
    ],
    files: [],
  },
  {
    uuid: generateUUIDv7(),
    name: 'Educational Technology',
    abbreviation: 'ET',
    version: '1.0',
    description: 'Technology for teaching and learning in classrooms',
    creator: 'System',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    properties: [
      {
        uuid: generateUUIDv7(),
        key: 'Technology Type',
        values: [{ uuid: generateUUIDv7(), value: 'Variable', files: [] }],
        files: [],
      },
      {
        uuid: generateUUIDv7(),
        key: 'Manufacturer',
        values: [{ uuid: generateUUIDv7(), value: 'Variable', files: [] }],
        files: [],
      },
      {
        uuid: generateUUIDv7(),
        key: 'Model',
        values: [{ uuid: generateUUIDv7(), value: 'Variable', files: [] }],
        files: [],
      },
      {
        uuid: generateUUIDv7(),
        key: 'Installation Date',
        values: [{ uuid: generateUUIDv7(), value: 'Variable', files: [] }],
        files: [],
      },
      {
        uuid: generateUUIDv7(),
        key: 'Warranty Expiration',
        values: [{ uuid: generateUUIDv7(), value: 'Variable', files: [] }],
        files: [],
      },
    ],
    files: [],
  },
  {
    uuid: generateUUIDv7(),
    name: 'Plumbing System',
    abbreviation: 'PS',
    version: '1.0',
    description: 'Water supply and drainage systems',
    creator: 'System',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    properties: [
      {
        uuid: generateUUIDv7(),
        key: 'System Type',
        values: [{ uuid: generateUUIDv7(), value: 'Variable', files: [] }],
        files: [],
      },
      {
        uuid: generateUUIDv7(),
        key: 'Material',
        values: [{ uuid: generateUUIDv7(), value: 'Variable', files: [] }],
        files: [],
      },
      {
        uuid: generateUUIDv7(),
        key: 'Installation Date',
        values: [{ uuid: generateUUIDv7(), value: 'Variable', files: [] }],
        files: [],
      },
      {
        uuid: generateUUIDv7(),
        key: 'Service Area',
        values: [{ uuid: generateUUIDv7(), value: 'Variable', files: [] }],
        files: [],
      },
      {
        uuid: generateUUIDv7(),
        key: 'Maintenance Schedule',
        values: [{ uuid: generateUUIDv7(), value: 'Variable', files: [] }],
        files: [],
      },
    ],
    files: [],
  },
  {
    uuid: generateUUIDv7(),
    name: 'Electrical System',
    abbreviation: 'ES',
    version: '1.0',
    description: 'Electrical distribution and power systems',
    creator: 'System',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    properties: [
      {
        uuid: generateUUIDv7(),
        key: 'System Type',
        values: [{ uuid: generateUUIDv7(), value: 'Variable', files: [] }],
        files: [],
      },
      {
        uuid: generateUUIDv7(),
        key: 'Capacity',
        values: [{ uuid: generateUUIDv7(), value: 'Variable', files: [] }],
        files: [],
      },
      {
        uuid: generateUUIDv7(),
        key: 'Installation Date',
        values: [{ uuid: generateUUIDv7(), value: 'Variable', files: [] }],
        files: [],
      },
      {
        uuid: generateUUIDv7(),
        key: 'Service Area',
        values: [{ uuid: generateUUIDv7(), value: 'Variable', files: [] }],
        files: [],
      },
      {
        uuid: generateUUIDv7(),
        key: 'Backup Systems',
        values: [{ uuid: generateUUIDv7(), value: 'Variable', files: [] }],
        files: [],
      },
    ],
    files: [],
  },
  {
    uuid: generateUUIDv7(),
    name: 'Sports Facility',
    abbreviation: 'SF',
    version: '1.0',
    description: 'Athletic facilities for physical education and sports',
    creator: 'System',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    properties: [
      {
        uuid: generateUUIDv7(),
        key: 'Facility Type',
        values: [{ uuid: generateUUIDv7(), value: 'Variable', files: [] }],
        files: [],
      },
      {
        uuid: generateUUIDv7(),
        key: 'Size',
        values: [{ uuid: generateUUIDv7(), value: 'Variable', files: [] }],
        files: [],
      },
      {
        uuid: generateUUIDv7(),
        key: 'Surface Type',
        values: [{ uuid: generateUUIDv7(), value: 'Variable', files: [] }],
        files: [],
      },
      {
        uuid: generateUUIDv7(),
        key: 'Equipment',
        values: [{ uuid: generateUUIDv7(), value: 'Variable', files: [] }],
        files: [],
      },
      {
        uuid: generateUUIDv7(),
        key: 'Maintenance Schedule',
        values: [{ uuid: generateUUIDv7(), value: 'Variable', files: [] }],
        files: [],
      },
    ],
    files: [],
  },
]
