version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: iob_redis
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data
    command: redis-server --save 60 1 --loglevel warning
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - iob_network

networks:
  iob_network:
    driver: bridge

volumes:
  redis-data:
    driver: local
